// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBys11mWgYRJKeSp75Nswj1ZCDgRZ931KY',
    appId: '1:946789037169:web:1a5492f6e9eac5a91c97d0',
    messagingSenderId: '946789037169',
    projectId: 'app-chat-ec51a',
    authDomain: 'app-chat-ec51a.firebaseapp.com',
    storageBucket: 'app-chat-ec51a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoCGscqnq1arFZIHBuk6754IoE_w7SLsg',
    appId: '1:946789037169:android:7a09d643bdf74ca31c97d0',
    messagingSenderId: '946789037169',
    projectId: 'app-chat-ec51a',
    storageBucket: 'app-chat-ec51a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHW0BuH7e4Rg7V0LdX0dtT3GPs1DrQFLg',
    appId: '1:946789037169:ios:1e6c4d19ddd7bd461c97d0',
    messagingSenderId: '946789037169',
    projectId: 'app-chat-ec51a',
    storageBucket: 'app-chat-ec51a.firebasestorage.app',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHW0BuH7e4Rg7V0LdX0dtT3GPs1DrQFLg',
    appId: '1:946789037169:ios:1e6c4d19ddd7bd461c97d0',
    messagingSenderId: '946789037169',
    projectId: 'app-chat-ec51a',
    storageBucket: 'app-chat-ec51a.firebasestorage.app',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBys11mWgYRJKeSp75Nswj1ZCDgRZ931KY',
    appId: '1:946789037169:web:71ca48940b40e38d1c97d0',
    messagingSenderId: '946789037169',
    projectId: 'app-chat-ec51a',
    authDomain: 'app-chat-ec51a.firebaseapp.com',
    storageBucket: 'app-chat-ec51a.firebasestorage.app',
  );
}
